# Generated by Django 5.0.2 on 2024-02-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_modules', '0001_initial'),
    ]

   
    def insertData(apps, schema_editor):

        SignatureColors = apps.get_model('site_modules','SignatureColors')

        # declare titles and colors
        titles = ['Musician', 'Band', 'Studio', 'Stage', 'Store']
        colors = ['10ACDD', 'E37056', 'FF8514', 'E558C6', '12C59A' ]

        # insert data
        for index in range(5):
            new_tag = SignatureColors(title = titles[index], color = '#' + colors[index])
            new_tag.save()

    operations = [
         migrations.RunPython(insertData),
    ]
