# Generated by Django 5.0.2 on 2024-06-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
