# Generated by Django 5.0.2 on 2024-02-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    def insert_Genres(apps, schema_editor):

        Genre = apps.get_model('genre','Genre')

        genres = [ 'Rock', 'Metal', 'Pop', 'Jazz', 'Stoner'     
        ]

        # insert all data
        for index in range(len(genres)):
            new_genre = Genre(genre = genres[index])
            new_genre.save()

    operations = [
        migrations.RunPython(insert_Genres),
    ]
