# Generated by Django 5.0.2 on 2024-02-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='hasMusicianProfile',
            new_name='musicianId',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hasStageProfile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hasStoreProfile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hasStudioProfile',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stageId',
            field=models.BooleanField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='storeId',
            field=models.BooleanField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='studioId',
            field=models.BooleanField(max_length=255, null=True),
        ),
    ]
