# Generated by Django 5.0.2 on 2024-03-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_hasmusicianprofile_customuser_musicianid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hasBandProfile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stageId',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='storeId',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='studioId',
        ),
    ]
