# Generated by Django 5.0.2 on 2024-05-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_hasbandprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stageId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='storeId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='studioId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
