# Generated by Django 5.0.2 on 2024-06-11 13:05

import django.db.models.deletion
import django.utils.timezone
import message.models
import studios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0003_allinstruments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.CharField(default=message.models.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=studios.models.Studio, related_name='receiver', to='musician.musician')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='musician.musician')),
            ],
        ),
    ]
