# Generated by Django 5.0.2 on 2024-06-11 12:04

import django.utils.timezone
import message.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.CharField(default=message.models.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
