# Generated by Django 5.0.2 on 2024-05-24 13:24

import band.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('bandId', models.CharField(default=band.models.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('category', models.CharField(default='band', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
