# Generated by Django 5.0.2 on 2024-05-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
