# Generated by Django 5.0.2 on 2024-03-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='user',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
