# Generated by Django 5.0.2 on 2024-03-28 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_insert_genres'),
        ('profiles', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id2', to='genre.genre')),
                ('musicianId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicianId2', to='profiles.musician')),
            ],
        ),
    ]
