# Generated by Django 5.0.2 on 2024-03-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_insert_genres'),
        ('profiles', '0004_musiciangenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiciangenre',
            name='genreId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id2', to='genre.genre'),
        ),
    ]
