# Generated by Django 5.0.2 on 2024-06-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_insert_genres'),
        ('profiles', '0005_insert_studio_services'),
    ]

    operations = [
    ]
