# Generated by Django 5.0.2 on 2024-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_genres_delete_genre_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genres',
            field=models.ManyToManyField(blank=True, to='profiles.genre'),
        ),
    ]
