# Generated by Django 5.0.2 on 2024-06-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_insert_studio_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='studio_services',
            field=models.ManyToManyField(blank=True, to='profiles.studio_services'),
        ),
    ]
