# Generated by Django 5.0.2 on 2024-07-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_insert_store_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=1000),
        ),
    ]
