# Generated by Django 5.0.2 on 2024-06-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_merge_0004_insert_genres_0005_insert_studio_services'),
        ('profiles', '0007_insert_instruments'),
    ]

    operations = [
    ]
