# Generated by Django 5.0.2 on 2024-04-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiciangenre',
            name='genreName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
