# Generated by Django 5.0.2 on 2024-04-20 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_instrument_musicianinstrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianinstrument',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument', to='profiles.instrument'),
        ),
        migrations.AlterField(
            model_name='musicianinstrument',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musician', to='profiles.musician'),
        ),
    ]
