# Generated by Django 5.0.2 on 2024-04-20 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_musicianinstrument_instrument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='profiles.musician')),
            ],
        ),
    ]
