# Generated by Django 5.0.2 on 2024-05-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_song'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
