# Generated by Django 5.0.2 on 2024-05-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_delete_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicianInstrument',
        ),
    ]
