# Generated by Django 5.0.2 on 2024-05-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_delete_musicianinstrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusInst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument', to='profiles.instrument')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musician', to='profiles.musician')),
            ],
        ),
    ]
