# Generated by Django 5.0.2 on 2024-05-06 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_musinst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musinst',
            name='instrument',
        ),
        migrations.AlterField(
            model_name='musinst',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skata', to='profiles.musician'),
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
