# Generated by Django 5.0.2 on 2024-05-16 16:31

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeId', models.CharField(default=store.models.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('websiteLink', models.URLField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(default='store', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
