# Generated by Django 5.0.2 on 2024-06-03 17:27

import django.db.models.deletion
import django.utils.timezone
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(default=posts.models.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('profile_id', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('musician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musician', to='musician.musician')),
            ],
        ),
    ]
