# Generated by Django 5.0.2 on 2024-04-24 18:34

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(default=posts.models.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('profile_id', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
            ],
        ),
    ]
