# Generated by Django 5.0.2 on 2024-06-21 08:19

import django.db.models.deletion
import django.utils.timezone
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0007_insert_store_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryId', to='profiles.category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(default=posts.models.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.profile')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post_title')),
            ],
        ),
    ]
