# Generated by Django 5.0.2 on 2024-06-03 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_genre'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='musician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musician', to='musician.musician'),
        ),
    ]
