# Generated by Django 5.0.2 on 2024-06-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_store'),
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='stage.stage'),
        ),
    ]
