# Generated by Django 5.0.2 on 2024-06-08 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
        ('posts', '0005_post_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band', to='band.band'),
        ),
    ]
