# Generated by Django 5.0.2 on 2024-06-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=40)),
            ],
        ),
    ]
