# Generated by Django 5.0.2 on 2024-06-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='posts.post_title'),
        ),
    ]
