# Generated by Django 5.0.2 on 2024-06-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_title2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title2',
            new_name='title',
        ),
    ]
