# Generated by Django 5.0.2 on 2024-06-08 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_title2_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
