# Generated by Django 5.0.2 on 2024-06-17 18:00

import django.db.models.deletion
import django.utils.timezone
import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_insert_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.CharField(default=event.models.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='profiles.profile')),
                ('main_bands', models.ManyToManyField(related_name='main_bands', to='profiles.profile')),
                ('profile_location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_location', to='profiles.profile')),
                ('support_acts', models.ManyToManyField(blank=True, related_name='support_acts', to='profiles.profile')),
            ],
        ),
    ]
