# Generated by Django 5.0.2 on 2024-06-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('profiles', '0004_insert_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bands',
        ),
        migrations.AddField(
            model_name='event',
            name='main_bands',
            field=models.ManyToManyField(blank=True, related_name='main_bands', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='support_acts',
            field=models.ManyToManyField(blank=True, related_name='support_acts', to='profiles.profile'),
        ),
    ]
