# Generated by Django 5.0.2 on 2024-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_bands_event_main_bands_and_more'),
        ('profiles', '0004_insert_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_bands',
            field=models.ManyToManyField(related_name='main_bands', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_acts',
            field=models.ManyToManyField(related_name='support_acts', to='profiles.profile'),
        ),
    ]
