# Generated by Django 5.0.2 on 2024-06-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='profile_location',
        ),
    ]
