# Generated by Django 5.0.2 on 2024-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_main_bands_alter_event_support_acts'),
        ('profiles', '0004_insert_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='support_acts',
            field=models.ManyToManyField(blank=True, related_name='support_acts', to='profiles.profile'),
        ),
    ]
